apps/urls.py
from django.urls import path

from . import views

app_name = 'apps'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote', views.vote, name='vote')
]

myblog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('apps/', include('apps.urls')),
    path('admin/', admin.site.urls),
]

apps/models.py
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    # 设置方法以什么字段排序
    was_published_recently.admin_order_field = 'pub_date'
    #
    was_published_recently.boolean = True
    # 方法的显示名称
    was_published_recently.short_description = 'published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice

apps/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'apps/index.html'
    context_object_name = 'last'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'apps/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'apps/results.html'
# Create your views here.
# def index(request, **kwargs):
#     last = Question.objects.order_by('-pub_date')[:5]
#     context = {'last': last}
#
#     #output = ','.join([q.question_text for q in last])
#     # response = HttpResponse('hello this is index %s' % kwargs)
#     #return HttpResponse(output)
#     return render(request, 'apps/index.html', context)
#
#
# def detail(request, question_id):
#     # return HttpResponse('this is look detail %s' % question_id)
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404('%s not exist' % question_id)
#     # return render(request, 'apps/detail.html', {'question': question})
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'apps/detail.html', {'question': question})
#
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'apps/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'apps/detail.html', {
            'question': question,
            'errMessage': 'you didn`t not choice'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('apps:results', args=(question_id,)))

apps/templates/apps/detail.html
<h1>{{ question.question_text }}</h1>
{% if errMessage %}
    <p><strong>{{ errMessage }}</strong></p>
{% endif %}
<form action="{% url 'apps:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice {{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice {{ forloop.counter }}">{{ choice.choice }}</label>
    {% endfor %}
    <input type="submit" value="vote">
</form>

apps/templates/apps/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'apps/style.css' %}">

{% if last %}
    <ul>
    {% for question in last  %}
        <li><a href="{% url 'apps:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% endif %}

apps/templates/apps/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice }}---{{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>